const ActionTypes = {
    SET_CURRENT_STEP: 'SET_CURRENT_STEP',
    UPDATE_STEP_ONE: 'UPDATE_STEP_ONE',
    UPDATE_STEP_TWO: 'UPDATE_STEP_TWO',
    UPDATE_STEP_THREE: 'UPDATE_STEP_THREE',
    SET_USER: 'SET_USER',
    RESET_USER: 'RESET_USER',
    SET_AUTH: 'SET_AUTH',
    INCREMENT_STEP: 'INCREMENT_STEP',
    CREATE_EVENT: 'CREATE_EVENT',
    FETCH_USER_DATA_ERROR: "FETCH_USER_DATA_ERROR"
};

export default ActionTypes;
